### ISSUE TITLE
insecure ?

### ISSUE THREAD

**Issue by beylerian** [madvas/gae-init#10]
I haven't tested yet but in base.html
the JS in the bottom seems to openly dump your app config which includes salt and flask secret.
these maybe shouldn't be stored/accessed like this, just saying

> module.value('gaAppConfig', {{ app_config | tojson | safe }});

**Comment by TBxy** [comment]
Salt and flask secret is only loaded for users with admin right. 
Is it still an issue? What would be a better approach?

**Comment by beylerian** [comment]
Hey TB you are right, I just find it a bit weird that the config is dumped i'll do some more testing on that and try to find a better way
